name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push_to_registries:
    name: Publish module to Github Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm publish
